receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Refer to configurations/schema.yaml for configuration options
  presidio_redaction:
    analyzer_endpoint: http://host.docker.internal:5002/analyze
    anonymizer_endpoint: http://host.docker.internal:5001/anonymize
    concurrency_limit: 1
    analyzer:
      language: "en"
      score_threshold: 0.5
    anonymizer:
      anonymizers:
        - entity: "DEFAULT"
          type: "REPLACE"
          new_value: "REDACTED"
    process_trace_if:
      - 'resource.attributes["service.name"] == "python-tracing-sample" and attributes["contains_pii"] == true'
    process_log_if:
      - 'resource.attributes["service.name"] == "python-tracing-sample" and severity_text == "INFO"'

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
