receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Refer to schema.yaml for configuration options
  presidio_redaction:
<<<<<<< Updated upstream
    mode: "embedded"
    error_mode: "propagate"
=======
    run_mode: "embedded"
>>>>>>> Stashed changes
    analyzer:
      language: "en"
      score_threshold: 0.5
    anonymizer:
      anonymizers:
<<<<<<< Updated upstream
        - entity: "DEFAULT"
          type: "REPLACE"
          new_value: "REDACTED"
=======
        - entity: "default"
          type: "REPLACE"
          new_value: "REDACTED"

>>>>>>> Stashed changes
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]