receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Refer to schema.yaml for configuration options
  presidio_redaction:
    presidio_service:
      use_docker: false
      docker_analyzer_endpoint: http://host.docker.internal:5002/analyze
      docker_anonymizer_endpoint: http://host.docker.internal:5001/anonymize
      concurrency_limit: 1 # Default to 1, pending https://github.com/microsoft/presidio/pull/1497
      python_path: "/"
    analyzer:
      language: "en"
      score_threshold: 0.5
    anonymizer:
      anonymizers:
        - entity: "DEFAULT"
          type: "HASH"
          hash_type: "sha256"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
