receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Refer to schema.yaml for configuration options
  presidio_redaction:
    mode: "embedded"
    error_mode: "propagate"
    presidio_service:
      # If you use external Presidio services (mode = "external"), you must specify the presidio endpoints here
      # analyzer_endpoint: http://host.docker.internal:5002/analyze
      # anonymizer_endpoint: http://host.docker.internal:5001/anonymize
      concurrency_limit: 1
    analyzer:
      language: "en"
      score_threshold: 0.5
    anonymizer:
      anonymizers:
        - entity: "default"
          type: "HASH"
          hash_type: "sha256"
#    process_trace_if:
# - 'resource.attributes["service.name"] == "python-tracing-sample" and attributes["contains_pii"] == true'
#    process_log_if:
# - 'resource.attributes["service.name"] == "python-tracing-sample" and severity_text == "INFO"'

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [presidio_redaction]
      exporters: [debug]
