services:
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:2.2.355
    container_name: presidio-analyzer
    ports:
      - "5002:3000"

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:2.2.355
    container_name: presidio-anonymizer
    ports:
      - "5001:3000"

  otel-collector:
    image: collector-local:latest
    container_name: otel-collector
    build:
      context: ../
      dockerfile: ./docker/CollectorOnly.local.Dockerfile
    ports:
      - "4318:4318" # HTTP endpoint for traces and metrics
      - "4317:4317" # gRPC endpoint for traces and metrics
    volumes:
      - type: bind
        source: ./otel-config.yaml
        target: /app/config.yaml
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer

  # basic-python-app:
  #   image: python:3.9-slim
  #   volumes:
  #     - .:/workspace
  #   working_dir: /workspace
  #   entrypoint: ["/bin/bash", "-c"]
  #   command: ["tail -f /dev/null"]
