# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import presidio_pb2 as presidio__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in presidio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PresidioRedactionProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/PresidioRedactionProcessor/Analyze',
                request_serializer=presidio__pb2.PresidioAnalyzerRequest.SerializeToString,
                response_deserializer=presidio__pb2.PresidioAnalyzerResponses.FromString,
                _registered_method=True)
        self.Anonymize = channel.unary_unary(
                '/PresidioRedactionProcessor/Anonymize',
                request_serializer=presidio__pb2.PresidioAnonymizerRequest.SerializeToString,
                response_deserializer=presidio__pb2.PresidioAnonymizerResponse.FromString,
                _registered_method=True)
        self.AnalyzeAndAnonymize = channel.unary_unary(
                '/PresidioRedactionProcessor/AnalyzeAndAnonymize',
                request_serializer=presidio__pb2.PresidioAnalyzerAnomymizerRequest.SerializeToString,
                response_deserializer=presidio__pb2.PresidioAnonymizerResponse.FromString,
                _registered_method=True)


class PresidioRedactionProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Anonymize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAndAnonymize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PresidioRedactionProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=presidio__pb2.PresidioAnalyzerRequest.FromString,
                    response_serializer=presidio__pb2.PresidioAnalyzerResponses.SerializeToString,
            ),
            'Anonymize': grpc.unary_unary_rpc_method_handler(
                    servicer.Anonymize,
                    request_deserializer=presidio__pb2.PresidioAnonymizerRequest.FromString,
                    response_serializer=presidio__pb2.PresidioAnonymizerResponse.SerializeToString,
            ),
            'AnalyzeAndAnonymize': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAndAnonymize,
                    request_deserializer=presidio__pb2.PresidioAnalyzerAnomymizerRequest.FromString,
                    response_serializer=presidio__pb2.PresidioAnonymizerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PresidioRedactionProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PresidioRedactionProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PresidioRedactionProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PresidioRedactionProcessor/Analyze',
            presidio__pb2.PresidioAnalyzerRequest.SerializeToString,
            presidio__pb2.PresidioAnalyzerResponses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Anonymize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PresidioRedactionProcessor/Anonymize',
            presidio__pb2.PresidioAnonymizerRequest.SerializeToString,
            presidio__pb2.PresidioAnonymizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAndAnonymize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PresidioRedactionProcessor/AnalyzeAndAnonymize',
            presidio__pb2.PresidioAnalyzerAnomymizerRequest.SerializeToString,
            presidio__pb2.PresidioAnonymizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
