name: Build and Push Docker Image With Presidio

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Log into Docker Hub (remove this step if you do NOT want to push)
      - name: Log in to Docker Hubs
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          # Path to the directory containing your Dockerfile
          context: .
          # Specify the path to your Dockerfile relative to the repository root
          file: docker/CollectorWithPresidio.Dockerfile
          platforms: linux/amd64
          push: true # set to false if you only want to build without pushing
          tags: |
            rohankapadia/presidioredactioncollector:withpresidio
            rohankapadia/presidioredactioncollector:withpresidio-${{ github.sha }}
