name: Build and Push Docker Image With Presidio

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use local module
        run: |
          # Add a replaces section to the builder-config.yaml
          echo "" >> docker/builder-config.yaml
          cat >> docker/builder-config.yaml <<EOF
          replaces:
            - github.com/RKapadia01/PresidioRedactionProcessor/presidioredactionprocessor => ../presidioredactionprocessor
          EOF

          cat docker/builder-config.yaml

      - name: Log in to Docker Hubs
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/CollectorWithPresidio.Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            rohankapadia/presidioredactioncollector:withpresidio
            rohankapadia/presidioredactioncollector:withpresidio-${{ github.sha }}
          build-args: |
            GITHUB_SHA=${{ github.sha }}